name: Deploy Images to S3

# on:
#   push:
#     branches:
#       - main  # change to your default branch

on:
  workflow_dispatch: # ðŸ‘ˆ makes it manual
    inputs:
      environment:
        description: "Environment to deploy images"
        required: true
        default: "production"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync images to S3
        run: |
          aws s3 sync ./assets/images s3://${{ secrets.S3_BUCKET }}/images --delete --acl public-read
